# Generated by Django 3.0.8 on 2020-07-21 06:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.CharField(max_length=48)),
                ('code', models.CharField(max_length=255)),
                ('criticalStock', models.BooleanField()),
                ('criticalStockAmt', models.IntegerField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='images')),
                ('vendor', models.CharField(max_length=200)),
                ('dateBought', models.DateField()),
                ('regDate', models.DateField(default=datetime.datetime(2020, 7, 21, 6, 28, 47, 541952))),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('editor', models.CharField(max_length=200)),
                ('invoiceCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceCode', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('sum', models.IntegerField()),
                ('taxNo', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urun', to='accounts.Product')),
            ],
        ),
    ]
