# Generated by Django 3.0.8 on 2020-07-21 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='criticalStockAmt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='regDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 7, 30, 19, 37385)),
        ),
    ]
