# Generated by Django 3.0.8 on 2020-07-21 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200721_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='regDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 7, 32, 27, 450722)),
        ),
    ]
