# Generated by Django 3.0.8 on 2020-07-21 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200721_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sum',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='regDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 8, 4, 11, 29811)),
        ),
    ]
