# Generated by Django 3.0.8 on 2020-09-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200831_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='productsLeft',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
