# Generated by Django 3.0.8 on 2020-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200721_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateBought',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='regDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
