# Generated by Django 3.0.8 on 2020-09-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_logs_productsleft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='lastStocktakeTime',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lastStocktakeTime',
        ),
        migrations.AddField(
            model_name='logs',
            name='lastStocktakeTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
