# Generated by Django 3.0.8 on 2020-07-21 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200721_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateBought',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='regDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 21, 8, 11, 1, 270250)),
        ),
    ]
