# Generated by Django 3.0.8 on 2020-09-01 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20200901_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLogs',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.BooleanField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('editor', models.CharField(max_length=200)),
                ('logDate', models.DateTimeField(blank=True, editable=False, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('company', models.CharField(max_length=200)),
                ('dateBought', models.DateField(blank=True, null=True)),
                ('productsLeft', models.IntegerField(blank=True, null=True)),
                ('lastStocktakeTime', models.DateTimeField(blank=True, null=True)),
                ('history_change_reason', models.TextField(max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Invoice')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.Product')),
            ],
            options={
                'verbose_name': 'historical logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
