# Generated by Django 3.0.8 on 2020-07-21 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200721_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dateBought',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 21, 8, 13, 55, 489311)),
        ),
    ]
