# Generated by Django 3.0.8 on 2020-07-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200722_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invoiceCode',
        ),
    ]
