# Generated by Django 3.0.8 on 2020-07-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200722_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urun', to='accounts.Product'),
        ),
    ]
