# Generated by Django 3.0.8 on 2020-07-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200722_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='accounts.Invoice'),
        ),
    ]
