# Generated by Django 3.0.8 on 2020-07-23 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200723_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fatura', to='accounts.Product'),
        ),
    ]
