# Generated by Django 3.0.8 on 2020-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200723_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='criticalStock',
            field=models.BooleanField(default=False),
        ),
    ]
