# Generated by Django 3.0.8 on 2020-08-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_historicalinvoice_historicalproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalInvoice',
        ),
    ]
