# Generated by Django 3.0.8 on 2020-08-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_historicalinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_change_reason',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
