# Generated by Django 3.0.8 on 2020-08-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20200807_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='lastStocktakeTime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='lastStocktakeTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
