# Generated by Django 3.0.8 on 2020-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200821_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='lastStocktakeTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lastStocktakeTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
